"""bz/predict on real conversations from the feed (other teams' included). python3 tests/test_predict.py"""
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from bz.predict import (abuela_limit, abuela_next, abuela_path, advise, answers, chato_allowance,  # noqa: E402
                        chato_next, fit_chato)


def thread(seq, dealer="abuela", side="buy", kind="buy:pack:sobre_barrio", deal=None, tid=1):
    return {"id": tid, "team": "tX", "dealer": dealer, "kind": kind, "side": side, "deal": deal,
            "seq": [("D", x[1:], False) if isinstance(x, str) and x[0] == "D" else x for x in seq]}


def D(p, final=False):
    return ("D", p, final)


def U(p):
    return ("U", p)


checks = 0
# 1. Abuela, thread 166 (t04, pack): 30, then 25 -> her limit is 19 or 20. She went 24, 23, 22, 21, 20 (final).
assert abuela_limit(30, 25, "buy") == (19, 20); checks += 1
assert abuela_path(30, 20, "buy", 6) == [25, 24, 23, 22, 21, 20]; checks += 1
# 2. Thread 271 (t12, pack): 30, 25, 23, 22, 21, 20, 19 (final). Same first answer, limit 19: the 2 P step shows it.
assert abuela_path(30, 19, "buy", 6) == [25, 23, 22, 21, 20, 19]; checks += 1
# 3. Thread 165 (ours): her first answer 27 -> limit 23-24. She never took our 19, 20 or 21.
assert abuela_limit(30, 27, "buy") == (23, 24); checks += 1
# 4. First concession is half the way to her limit, rounded down: from 30 with limit 20 -> 25, limit 21 -> 26.
assert abuela_next(30, 20, "buy", first=True) == 25 and abuela_next(30, 21, "buy", first=True) == 26; checks += 1
# 5. When she buys from us the direction flips: sell an uncommon, 12 then 13 -> her limit (her best bid) is 14-15.
assert abuela_limit(12, 13, "sell") == (15, 14); checks += 1
assert abuela_next(13, 15, "sell") == 14; checks += 1

# 6. answers(): a repeated or lower price is no move; her greeting is not an answer.
t = thread([U(27), D(30), U(27), D(30), U(2), D(30), U(16), D(26)])  # thread 109 (t06)
opening, ans = answers(t)
assert opening == 30 and [a.step for a in ans] == [0, 0, 14] and ans[-1].conc == 4, ans; checks += 1

# 7. El Chato, thread 234 (t03, uncommon): steps of 1, he holds 33 twice, then 1 P per answer: 32, 31, 30, 29 (final).
a, b = 0.10, 0.5
conceded, her, got = 0, 33, []
for k, step in enumerate([None, 1, 1, 1, 1, 1], 1):
    nxt = chato_next(her, conceded, k, step, a, b, "buy")
    conceded += her - nxt
    her = nxt
    got.append(her)
assert got == [33, 33, 32, 31, 30, 29], got; checks += 1
# 8. Thread 223 (t12, rare): we jump 22 then 14, he gives only 1 then 3: his schedule, not our step, binds.
a, b = 0.42, 0.5
assert [chato_allowance(k, a, b) for k in (1, 2, 3, 4)] == [0, 2, 4, 7]; checks += 1
assert chato_next(96, 1, 2, 22, a, b, "buy") == 95; checks += 1
# 9. ...and our small step binds when it is below his schedule: thread 286, steps of 2 late on, 2 P each.
assert chato_next(93, 4, 4, 2, a, b, "buy") == 91; checks += 1

# 10. fit_chato recovers the schedule from conversations generated by it.
def chato_conv(steps, a, b, opening=97, tid=1):
    seq, ours, her, conceded = [D(opening)], 50, opening, 0
    for k, step in enumerate(steps, 1):
        ours += step or 0
        seq.append(U(ours))
        nxt = chato_next(her, conceded, k, step if k > 1 else None, a, b, "buy")
        conceded += her - nxt
        her = nxt
        seq.append(D(her))
    return thread(seq, dealer="chato", kind="buy:rare", tid=tid)


convs = [chato_conv([5, 5, 5, 5, 5, 5, 5], 0.42, 0.5, tid=i) for i in range(4)]
a, b = fit_chato(convs)["buy:rare"]
assert all(chato_allowance(k, a, b) == chato_allowance(k, 0.42, 0.5) for k in range(1, 8)), (a, b); checks += 1


# 11. advise() against a simulated Abuela: any limit, any patience 4-7. Every price is a move, never above
#     what she would say next, and we end within 1 P of her limit as soon as her patience allows.
def abuela_sim(limit, patience, opening=30, our_limit=28):
    hist, her, seen = [], opening, set()
    for n in range(1, 12):
        adv = advise("abuela", "buy", "buy:pack:sobre_barrio", opening, hist, our_limit)
        if adv["action"] == "accept":
            return adv["price"], n
        p = adv["price"]
        assert p not in seen, (p, hist)  # no repeats: a repeated price earns nothing and she calls it spam
        seen.add(p)
        nxt = abuela_next(her, limit, "buy", first=not hist)
        if p >= nxt and p >= limit:  # she takes our offer
            return p, n
        her = nxt
        hist.append((p, her))
        if n >= patience or her == limit:  # her final: we take it
            return her, n
    return her, n


random.seed(7)
for _ in range(200):
    limit, patience = random.randint(19, 24), random.randint(4, 7)
    price, n = abuela_sim(limit, patience)
    assert limit <= price, (limit, patience, price)
    if patience >= 7:
        assert price <= limit + 1, (limit, patience, price)
checks += 1


# 12. advise() against a simulated El Chato (his rare schedule): every price moves towards him, and with his
#     patience at 6+ answers we beat the 84 we got in thread 526 with steps of 4.
def chato_sim(patience, a=0.48, b=0.5, opening=97):
    hist, her, conceded, ours = [], opening, 0, None
    for k in range(1, 14):
        p = advise("chato", "buy", "buy:rare", opening, hist, 100)["price"]
        assert ours is None or p > ours, (k, p, ours)
        nxt = chato_next(her, conceded, k, None if ours is None else p - ours, a, b, "buy")
        if p >= nxt:  # he takes our offer
            return p
        conceded, her, ours = conceded + her - nxt, nxt, p
        hist.append((p, her))
        if k >= patience:
            return her
    return her


assert [chato_sim(k) for k in (4, 5)] == [89, 85] and all(chato_sim(k) < 84 for k in (6, 7, 8, 9)); checks += 1

# 13. family_of(): it recovers each known dealer's family from conversations alone, and refuses to guess
#     with fewer than 3 conversations where the dealer moved.
from bz.predict import family_of  # noqa: E402
fake = [dict(c, dealer="nuevo") for c in convs]  # 4 Boulware conversations from check 10
assert family_of("nuevo", fake) == {"buy:rare": "boulware"}, family_of("nuevo", fake)
assert family_of("nuevo", fake[:2]) == {"buy:rare": None}; checks += 1

# 14. Pilar (linear), thread 778 (ours, MAL-08): 16 held on her first answer, then 1 P per move: 17 ... 21 (final).
t = thread([U(30), D(16), U(28), D(16), U(27), D(17), U(26), D(18), U(25), D(19), U(24), D(20), U(23), D(21, True)],
           dealer="pilar", side="sell", kind="sell:uncommon")
opening, ans = answers(t)
assert opening == 16 and [a.conc for a in ans] == [0, 1, 1, 1, 1, 1], ans
adv = advise("pilar", "sell", "sell:uncommon", 16, [(28, 16), (27, 17)], 15)
assert adv["price"] == 26 and adv["her_next"] == 18, adv  # 1 P closer, never crossing her next bid
adv = advise("pilar", "sell", "sell:uncommon", 16, [(28, 16), (19, 18)], 15)
assert adv["price"] == 19, adv  # no room left: offer her next price, she takes it
assert family_of("pilar", [dict(t, id=i) for i in range(3)]) == {"sell:uncommon": "linear"}; checks += 1

# 15. Don Ernesto (banco, Boulware), thread 1722 (t18 selling SAL-11, epic): steps of 2, he gave 0, 1, 1, then 2 each
#     time (never more than the step), 112 -> 126 (final). advisor() fits his schedule from his own conversations.
from bz.predict import MODELS, advisor  # noqa: E402
t = thread([D(112), U(232), D(112), U(230), D(113), U(228), D(114), U(226), D(116), U(224), D(118), U(222), D(120),
            U(220), D(122), U(218), D(124), U(216), D(126, True)], dealer="banco", side="sell", kind="sell:epic", tid=1722)
opening, ans = answers(t)
assert opening == 112 and [a.conc for a in ans] == [0, 1, 1, 2, 2, 2, 2, 2, 2], ans
assert all(a.conc <= a.step for a in ans if a.step is not None); checks += 1
assert MODELS["banco"] == "boulware"
live = {"messages": [{"id": i, "sender": "banco" if e[0] == "D" else "tX", "offer": {"give": {"cash": e[1]}}}
                     for i, e in enumerate(t["seq"][:5])]}  # 112, 232, 112, 230, 113: his turn is done, ours next
move = advisor("banco", "sell", "sell:epic", 120, threads=[t])(live)
assert move["action"] == "offer" and 120 <= move["price"] < 230, move  # a step towards him, never below our floor
assert advisor("banco", "sell", "sell:epic", 120, threads=[]) is not None; checks += 1  # MODELS: a model even without data

print(f"ok: {checks} checks")
